### ISSUE TITLE
Deploy live staging environment

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/push-messages#7] opened 2016-03-09 19:53 UTC
For https://github.com/mozilla-services/push-dev-dashboard/issues/87, I need a live staging environment of the push messages API talking to a live staging environment of autopush too.

**Comment by bbangert** [comment] 2016-03-14 21:02
Duplicate of https://github.com/mozilla-services/push-service/issues/25

**Closed as completed by bbangert** 2016-03-14 21:02 UTC
